<a href="https://colab.research.google.com/github/hyeeunun/-/blob/main/Numpy%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
#1.np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하고 내용을 출력하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.
import numpy as np
a = np.zeros((3,4))
print(a)

#2.위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용해 아래와 같은 값을 갖도록 초기화하고 내용을 출력하시오.
#array([[ 1.,  2.,  3.,  4.],[ 5.,  6.,  7.,  8.], [ 9., 10., 11., 12.]])
count = 1
for i in range(3):
  for j in range(4):
    a[i, j] = count
    count += 1
print(a)

#3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하여 출력하시오.
print(a[1, 2])

#4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하고 출력하시오.아래 결과에서 차원이 유지된 것에 주의하여 인덱싱을 하시오.
#array([[5., 6., 7., 8.]])
print(a[1:2, :])

#5.a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하고 결과를 출력하시오.
#array([[ 2.,  3.], [ 6.,  7.],[10., 11.]])
print(a[:, 1:3])

#6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하고 결과를 출력하시오.
#array([1., 2., 3., 4., 5., 6.])
print(a[a<=6])

#7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오.
#이 때 생성된 ndarray의 이름은 b가 되도록 한다.그리고 아래와 같이 랜덤 시드 설정을 7로 하고 실행하시오.
#np.random.seed(7)
np.random.seed(7)
b = np.random.rand(3, 4)
print(b)

#8. a와 b의 요소곱을 하여 c에 저장하고 결과를 출력하시오
c = a * b
print(c)

#9. b의 전치행렬을 구하여 d에 저장하고 결과를 출력하시오.
d = b.T
print(d)

#10. a와 d에 대하여 각 차원의 크기를 출력하시오.
print(a.shape, d.shape)

#11.a와 d의 행렬곱을 계산하여 e에 저장하고 결과를 출력하시오.
e = np.dot(a, d)
print(e)

#12. e에 대하여 각 열의 합을 계산하여 출력하시오.
print(np.sum(e, axis=0))


SyntaxError: invalid syntax (<ipython-input-31-d6f91a763be5>, line 5)